server:
  port: 8181
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:  
      routes:
        -  id: ATTENDANCE-SERVICE
           uri: http://localhost:7001
           predicates:
            - Path=/** 
        -  id: USER-SERVICE
           uri: http://localhost:7000
           predicates:
            - Path=/**